### PR TITLE
Disable "appendToLine" behaviour on Windows due to limit on hostnames per line

### PR DESCRIPTION
**Pull request by micdah**
On Windows there is a limitation on the number of hostnames per line (_hostnames over this limit are simply ignored_), but there is no such limit as long as you add each mapping on an individual line.

This pull request introduces `appendToLine` constant, which is set based on OS targeted - disabling the behaviour of appending to existing lines when compiled for Windows.

I have also updates the test cases to test in both scenarios (_which is the reason why the constant is declared as `var` so the test case can change it_).

### CODE REVIEW

**Comment by micdah** [comment]
Many of the diffs seem to be due to change in whitespace and formatting, I have applied `gofmt` to modified files

**Comment by rfay** [comment]
For the success of the PR, it would be better to gofmt in a separate PR.

A good PR should generally just provide changes that address the described problem.

You also accidentally checked in the .idea directory, please globally gitignore it.

**Comment by micdah** [comment]
I didn't accidentally include the `.idea/` folder, I explicitly included it and updated the `.gitignore` based on Jetbrains guide-lines, so all shared settings for any using an IdeaJ powered IDE can share settings.

I honestly doubt this will be merged, so the changes are a reflection of the code-changes I have done to our own production copy of the code - so on the slight off chance the maintainer is interested - they can have the changes. :smile:

**Comment by luthermonson** [comment]
@micdah @rfay I split off goodhosts into an org and added some if not all of the open PRs in this project. Lex is going to close this and link to the org if you'd like to come and try that and submit Issues and PRs against that you're more than welcome too: https://github.com/goodhosts/cli

**Comment by lextoumbourou** [comment]
Sorry for being a bad maintainer @micdah and @rfay . Thanks @luthermonson !

**Pull request closed without merging**
